[package]
name = "feistel-cipher"
version = "0.1.0"
authors = ["elr0p3 <ropefalora@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
clap = "2.33.3"
